language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: R+lFDGbwEUj09u0UPy1qHDGiu+w/S3ZgQfPv/hZzjXDDi1lXeZ1JG2Ud1CqqfiCl9tpwUKAPKFUk9vt54miUazJKm5yuE5uhHc7Kw1Rbm2qW1ExwDmm5sNB9tXdCEkgDDNeCOLBDRIITdmUkWO8wvp0tNzhI/l1kQvJVWAPMo6GRq2rXYCmn/xDGtdZRAwvO4rh+V8raJPyAQBDaKvEJAYCu6YsOlk6/3STX6PELrgavykychvc25acUkEjraLqt4/W5q8ex4EJFuRzJwRdlj6lU6AL305a1dR25YRemujM6K8vcONWmnX5+Gi3bPB4n9UYsPXYshTp+yvNJk59vdq//qmgVyyx5BmdzGgTGP3YqJHJ2s75VSQR2cKAWFWJhhBtzRIzqCh5X/BFnK3GWZAK51YK1tyVNh8zZVutTjBPJUYfS99kFXSRxjEXPsop4xVQlikMF87piyTAbVLsF/pRoc2Ir6eaEedDUxuhtJapPalrlD1gzJ+EDL7tmuj/mve9LaLgHenMpUm9cftJnux5eYcWY6kE6Ksc4hpesymGgVVdA7Sl7U5OAucQHdg3i3Ma5Iv3LF3XEtbXXbT9HGViCHOZLOnNCLFj3uVoZgokvBLFAnljuiBP+dvHeiLVN9Oj6YhNZKFIcmuH5ruXC898qgbiFdzQ6hH+dBgUenaA=
  - secure: GWL5QYm406G2Zyv+HlvBl7NIha9Kk9HQl7lFDXOt52+vgRQR/FcVre8U79geqF65SOVCOuTgRALoAqCYK0uWnM0qTXkRLCOHXffgNf7B7/uLfqKDOLb8jy2KXkuIIbRZu4kZr3lZxf+pQLdX7z17ohFiy0MAIr13YdsKsHNelpLvDCPQOv+fI7VJ5f5buk7xzUNR26S5G7S0Yj6qDrE11R47xmgmtT16IrHe3jF2JgMUXrzLwEfWf9ykWT+iCzY3XRvr8lKCfNhFjlbAaw4ib+cR0Y4Mb0MBLAvxilmVYhdnqaz74uN/s8dQO/o1zX7/egBEH+HwvWNeW/o0lPCU1XJrbW0Lqza/rNfXqbqq4/sJsnUJ7ZKnnZ4EUsbfV3siBnAqBHESQaIgBGXQkjvcNlINaVYoH7Pm1krD4OCNwbY/tq0bKRbnPwM49fhL4eoJ/EscTdyYg/0PgQhhi+JXlv538USqMS5Y2PWEvKs95H+yORIwcNiywnJU5oCtVet+fmsIx2oHpHp/8E8Wr09EQarmBr9QzhJ2rSEyYxa+NfirJoxQFnxDsepW3Huhgo4zVBKX4m1jPCR4x4LAHc+XDFCJTESytwpE0IrzuI9MphPlpV9MdXiHpKxyTtrI2gs4dnnIs7NPX3sIYyyzfsPWO7E1SE47L7rzKXsSyIWGEcM=
